Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -182,47 +182,48 @@ jobs:
         env:
           VID: ${{ secrets.APIID_VERACODE }}
           VKEY: ${{ secrets.APIKEY_VERACODE }}
-          ENVIRONMENT: ${{ inputs.environment }}
+          PROJECT: ${{ github.event.repository.name }}
+          BUILD_ID: ${{ github.run_id }}
+          BRANCH: ${{ github.ref_name }}
         run: |
-          # Verifica se existe um WAR
+          echo "Branch atual: $BRANCH"
+      
           WAR_FILE=$(find . -maxdepth 2 -name "*.war" | head -n 1)
           if [ -f "$WAR_FILE" ]; then
-            echo "Aplicação WAR detectada. Usando arquivo: $WAR_FILE"
             ARTIFACT="$WAR_FILE"
           else
-            # Procura por um JAR (excluindo o vosp-api-wrappers)
             JAR_FILE=$(find . -maxdepth 2 -name "*.jar" -not -name "vosp-api-wrappers*.jar" | head -n 1)
             if [ -f "$JAR_FILE" ]; then
-              echo "Java build detectado. Usando arquivo: $JAR_FILE"
               ARTIFACT="$JAR_FILE"
             else
-              echo "Nenhum WAR ou JAR encontrado. Usando analysisPack.zip."
               ARTIFACT="analysisPack.zip"
             fi
           fi
-       
-          if [ "$ENVIRONMENT" == "prod" ]; then
-            echo "Executando SAST em ambiente de produção..."
+      
+          if [ "$BRANCH" = "master" ]; then
+            echo "Executando SAST em produção (sem sandbox)..."
             java -jar vosp-api-wrappers-java-24.7.14.0.jar \
-              -vid $VID -vkey $VKEY \
+              -vid "$VID" -vkey "$VKEY" \
               -action uploadandscan \
-              -appname "${{ env.PROJECT }}" \
-              -version "${{ github.run_id }}" \
+              -appname "$PROJECT" \
+              -version "$BUILD_ID" \
               -filepath "$ARTIFACT" \
               -createprofile true \
               -deleteincompletescan 2 \
               -createsandbox false
-          else
-            echo "Executando SAST em ambiente de sandbox..."
+          elif [ "$BRANCH" = "develop" ]; then
+            echo "Executando SAST com sandbox QA..."
             java -jar vosp-api-wrappers-java-24.7.14.0.jar \
-              -vid $VID -vkey $VKEY \
+              -vid "$VID" -vkey "$VKEY" \
               -action uploadandscan \
-              -appname "${{ env.PROJECT }}" \
-              -version "${{ github.run_id }}" \
+              -appname "$PROJECT" \
+              -version "$BUILD_ID" \
               -filepath "$ARTIFACT" \
               -createprofile true \
               -deleteincompletescan 2 \
               -createsandbox true \
-              -sandboxname "QA" \
-              -debug
+              -sandboxname "QA"
+          else
+            echo "Branch desconhecida: $BRANCH. Abortando."
+            exit 1
           fi
